export const sampleMovies = [
  {
    id: 'local-1',
    title: 'The Great Wall',
    year: '2016',
    genre: 'Action, Adventure',
    language: 'English',
    rating: '6.5',
    releaseDate: '2016-12-16',
    description: 'A group of warriors protects the world from a mysterious threat near the Great Wall of China.',
    cast: 'Matt Damon, Jing Tian, Pedro Pascal',
    accent: 'linear-gradient(145deg, #8d1d1d, #242424 70%)',
  },
  {
    id: 'local-2',
    title: 'Patriots Day',
    year: '2016',
    genre: 'Drama, Thriller',
    language: 'English',
    rating: '7.4',
    releaseDate: '2016-12-21',
    description: 'A dramatized account of the events surrounding the Boston Marathon bombing and its aftermath.',
    cast: 'Mark Wahlberg, Kevin Bacon, John Goodman',
    accent: 'linear-gradient(145deg, #8b1010, #0c2747 68%)',
  },
  {
    id: 'local-3',
    title: 'Silence',
    year: '2016',
    genre: 'Drama, History',
    language: 'English',
    rating: '7.2',
    releaseDate: '2016-12-23',
    description: 'Two priests travel to Japan in search of their mentor while facing persecution and difficult choices.',
    cast: 'Andrew Garfield, Adam Driver, Liam Neeson',
    accent: 'linear-gradient(145deg, #d8eceb, #315e69 63%, #0e292e)',
  },
  {
    id: 'local-4',
    title: 'Why Him?',
    year: '2016',
    genre: 'Comedy',
    language: 'English',
    rating: '6.2',
    releaseDate: '2016-12-23',
    description: 'A protective father tries to deal with his daughter’s unconventional but wealthy boyfriend.',
    cast: 'James Franco, Bryan Cranston, Zoey Deutch',
    accent: 'linear-gradient(145deg, #4d4d4d, #1d1d1d)',
  },
  {
    id: 'local-5',
    title: '20th Century Women',
    year: '2016',
    genre: 'Comedy, Drama',
    language: 'English',
    rating: '7.3',
    releaseDate: '2016-12-28',
    description: 'A teenage boy grows up around three women who help him understand life and relationships.',
    cast: 'Annette Bening, Elle Fanning, Greta Gerwig',
    accent: 'linear-gradient(145deg, #d7d1c8, #7f6e60)',
  },
  {
    id: 'local-6',
    title: 'Colony',
    year: '2016',
    genre: 'Drama, Sci-Fi',
    language: 'English',
    rating: '7.1',
    releaseDate: '2016-01-14',
    description: 'A family navigates a divided Los Angeles where an occupying force controls the city.',
    cast: 'Josh Holloway, Sarah Wayne Callies, Peter Jacobson',
    accent: 'linear-gradient(145deg, #b9a27a, #3a2b27)',
  },
  {
    id: 'local-7',
    title: "Grey's Anatomy",
    year: '2016',
    genre: 'Drama',
    language: 'English',
    rating: '8.1',
    releaseDate: '2016-09-22',
    description: 'Doctors at a teaching hospital balance medicine, friendships, careers, and personal lives.',
    cast: 'Ellen Pompeo, Justin Chambers, Chandra Wilson',
    accent: 'linear-gradient(145deg, #152a59, #111111)',
  },
  {
    id: 'local-8',
    title: 'Resident Evil 6',
    year: '2016',
    genre: 'Action, Horror',
    language: 'English',
    rating: '5.5',
    releaseDate: '2016-01-21',
    description: 'A team of survivors continues a dangerous fight against a world-changing biological threat.',
    cast: 'Milla Jovovich, Iain Glen, Ali Larter',
    accent: 'linear-gradient(145deg, #d7cfaa, #4e4238)',
  },
  {
    id: 'local-9',
    title: 'Arrival',
    year: '2016',
    genre: 'Drama, Sci-Fi',
    language: 'English',
    rating: '7.9',
    releaseDate: '2016-11-11',
    description: 'A linguist works to communicate with mysterious visitors and understand why they have arrived.',
    cast: 'Amy Adams, Jeremy Renner, Forest Whitaker',
    accent: 'linear-gradient(145deg, #716c65, #171717)',
  },
  {
    id: 'local-10',
    title: 'Moonlight',
    year: '2016',
    genre: 'Drama',
    language: 'English',
    rating: '7.4',
    releaseDate: '2016-10-21',
    description: 'A young man experiences childhood, adolescence, and adulthood while searching for identity and belonging.',
    cast: 'Mahershala Ali, Trevante Rhodes, Naomie Harris',
    accent: 'linear-gradient(145deg, #172e7a, #090b29)',
  },
  {
    id: 'local-11',
    title: 'Passengers',
    year: '2016',
    genre: 'Adventure, Drama',
    language: 'English',
    rating: '7.0',
    releaseDate: '2016-12-21',
    description: 'Two travelers wake early on a deep-space journey and discover a problem threatening the ship.',
    cast: 'Jennifer Lawrence, Chris Pratt, Michael Sheen',
    accent: 'linear-gradient(145deg, #203c72, #0b0f22)',
  },
  {
    id: 'local-12',
    title: 'Hidden Figures',
    year: '2016',
    genre: 'Drama, History',
    language: 'English',
    rating: '7.8',
    releaseDate: '2017-01-06',
    description: 'Three brilliant women help drive a historic space program forward despite social barriers.',
    cast: 'Taraji P. Henson, Octavia Spencer, Janelle Monáe',
    accent: 'linear-gradient(145deg, #6d5137, #1f1b16)',
  },
];
